using System;
using Ai.SolidWorksAssistant.Cad;
using Xunit;

namespace Ai.SolidWorksAssistant.Tests
{
    public class MacroGenerationTests
    {
        private static MacroScript Generate(string planText, int opIndex)
        {
            var parsed = PlanParser.Parse(planText);
            Assert.False(parsed.HasErrors);
            return SwMacroGenerator.Generate(parsed.Plan.Operations[opIndex]);
        }

        [Fact]
        public void Rectangle_macro_converts_millimeters_to_meters()
        {
            var macro = Generate(TestPlans.SampleBracket, 0);

            // 100 mm -> 0.1, 50 mm -> 0.05 (invariant literals)
            Assert.Contains("CreateCornerRectangle", macro.Code);
            Assert.Contains(" 0.1, ", macro.Code);
            Assert.Contains(" 0.05, ", macro.Code);
        }

        [Fact]
        public void Rectangle_macro_selects_plane_and_toggles_sketch()
        {
            var macro = Generate(TestPlans.SampleBracket, 0);

            Assert.Contains("SelectByID2", macro.Code);
            Assert.Contains("\"PLANE\"", macro.Code);
            Assert.Contains("InsertSketch True", macro.Code);
        }

        [Fact]
        public void Extrude_macro_uses_FeatureExtrusion3_with_blind_depth()
        {
            var macro = Generate(TestPlans.SampleBracket, 1);

            Assert.Contains("FeatureExtrusion3", macro.Code);
            Assert.Contains(" 0.01, ", macro.Code); // 10 mm -> 0.01 m
            Assert.Contains("swFeat Is Nothing", macro.Code); // failure check present
        }

        [Fact]
        public void Through_hole_uses_through_all_end_condition_and_radius()
        {
            var macro = Generate(TestPlans.SampleBracket, 2);

            // T1 = 1 (swEndCondThroughAll)
            Assert.Contains("FeatureCut3", macro.Code);
            Assert.Contains("True, False, False, 1, 0,", macro.Code);
            // Ø10 -> radius 5 mm = 0.005 m
            Assert.Contains("CreateCircleByRadius 0.05, 0.025, 0#, 0.005", macro.Code);
        }

        [Fact]
        public void Every_macro_has_safe_main_structure()
        {
            var parsed = PlanParser.Parse(TestPlans.SampleBracket);
            foreach (var op in parsed.Plan.Operations)
            {
                var macro = SwMacroGenerator.Generate(op);
                Assert.Contains("Sub main()", macro.Code);
                Assert.Contains("On Error GoTo Fail", macro.Code);
                Assert.Contains("Application.SldWorks", macro.Code);
                Assert.Contains("ActiveDoc", macro.Code);
                Assert.Contains("End Sub", macro.Code);
                Assert.StartsWith("' Generated by AI SolidWorks Assistant", macro.Code);
            }
        }

        [Fact]
        public void Phase6_operation_throws_NotSupported()
        {
            var parsed = PlanParser.Parse("operation feature.fillet\nradius_mm = 3");
            Assert.Throws<NotSupportedException>(
                () => SwMacroGenerator.Generate(parsed.Plan.Operations[0]));
        }

        [Fact]
        public void Missing_numeric_param_is_caught()
        {
            // hole without diameter: validator catches it; generator must also refuse safely
            var parsed = PlanParser.Parse("operation feature.hole\nx = 5\ny = 5");
            Assert.Throws<InvalidOperationException>(
                () => SwMacroGenerator.Generate(parsed.Plan.Operations[0]));
        }
    }
}
